[default]
EXTERNAL_API_URL="http://api.openweathermap.org/data/2.5/weather"
API_KEY=""
APP_NAME="Weather Buddy API"

[development]
ENV_STATUS='On development'

[testing]
ENV_STATUS='On testing'

[production]
ENV_STATUS='On production'
